/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mycompany_myndklibapp_MyNativeClass */

#ifndef _Included_com_example_mycompany_myndklibapp_MyNativeClass
#define _Included_com_example_mycompany_myndklibapp_MyNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mycompany_myndklibapp_MyNativeClass
 * Method:    fourtyTwo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_mycompany_myndklibapp_MyNativeClass_fourtyTwo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
